FROM mediawiki:1.41

# Install PostgreSQL PHP driver. The upstream mediawiki image only ships
# mysqli + sqlite3; pgsql is required to use Render's managed Postgres.
RUN apt-get update \
    && apt-get install -y --no-install-recommends libpq-dev \
    && docker-php-ext-install pdo_pgsql pgsql \
    && apt-get purge -y --auto-remove libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# LocalSettings.php is not committed yet — it is generated by the
# installer wizard (/mw-config/) on first run and then committed
# (sanitized to read secrets from $_ENV) to this repo.
