FROM mediawiki:1.41

# Install PostgreSQL PHP driver. The upstream mediawiki image only ships
# mysqli + sqlite3; pgsql is required to use Render's managed Postgres.
#
# Pattern: install libpq5 (runtime) as manual, then libpq-dev (build only),
# compile extensions, then auto-remove build deps while keeping libpq5 so
# pgsql.so can still resolve -lpq at runtime.
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends libpq5; \
    savedAptMark="$(apt-mark showmanual)"; \
    apt-get install -y --no-install-recommends libpq-dev; \
    docker-php-ext-install pdo_pgsql pgsql; \
    apt-mark auto '.*' > /dev/null; \
    [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark > /dev/null; \
    apt-mark manual libpq5 > /dev/null; \
    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
    rm -rf /var/lib/apt/lists/*

# LocalSettings.php is not committed yet — it is generated by the
# installer wizard (/mw-config/) on first run and then committed
# (sanitized to read secrets from $_ENV) to this repo.
